// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	models "github.com/IBM/appconfiguration-go-sdk/lib/models"
	mock "github.com/stretchr/testify/mock"
)

// AppConfigurationInterface is an autogenerated mock type for the AppConfigurationInterface type
type AppConfigurationInterface struct {
	mock.Mock
}

// GetFeature provides a mock function with given fields: featureID
func (_m *AppConfigurationInterface) GetFeature(featureID string) (models.Feature, error) {
	ret := _m.Called(featureID)

	var r0 models.Feature
	if rf, ok := ret.Get(0).(func(string) models.Feature); ok {
		r0 = rf(featureID)
	} else {
		r0 = ret.Get(0).(models.Feature)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(featureID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFeatures provides a mock function with given fields:
func (_m *AppConfigurationInterface) GetFeatures() (map[string]models.Feature, error) {
	ret := _m.Called()

	var r0 map[string]models.Feature
	if rf, ok := ret.Get(0).(func() map[string]models.Feature); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.Feature)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
